project_id = "guvcwvqkxnrwcdmwbifh"

[functions.generate-sonic-pi]
verify_jwt = false

[functions.separate-stems]
verify_jwt = false

[functions.download-audio]
verify_jwt = false

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-api]
verify_jwt = false
